[IMP] runbot: add without-demo as field
odoo/runbot pull request #1001
Opened 2024-11-29 13:34 UTC by Williambraecky

Adds the without-demo flag as a field on config steps.

2024-11-29 13:35 UTC, Williambraecky commented on runbot/models/build_config.py
> +        if build.version_id.number >= '18.01' and self.with_demo:
This will not work obviously with the PR but I have no idea how we can make it work "temporarily"

2024-12-02 10:15 UTC, Xavier-Do requested changes

2024-12-02 10:15 UTC, Xavier-Do commented on runbot/models/build_config.py
> +    with_demo = fields.Boolean("Install demo data", default=True, tracking=True)
I'm not sure that having a default True is correct since we may want to have the default behaviour most of the time. (single module, testing, install of base database, at install, ....)

We may want to be able to force without in previous version, in this case the flag --without is already added 
We may want to force with demo on future version, but the only use case would be to have a database for the run (and maybe a nightly) and this will be a contionnal step. (have a database with demo for the running build) 

But adding it on the config could be a nice idea, I think that in this case we should also add support for `build.params_id.config_params.get('no_demo')`. But the field may be a selection field (default, no_demo, demo) so that the odoo testing can run without demo. Upgrade template will force "no demo" and master default config could install a template with demo on the side for the running build.

2024-12-02 10:15 UTC, Xavier-Do commented on runbot/models/build_config.py
> +            migrate_cmd.append('--without-demo=true')
```suggestion
        # Demo data behavior changed in 18.1 -> demo data became opt-in instead of opt-out
        available_options = build._parse_config()
        if self.with_demo and 'with-demo' in available_options:
            migrate_cmd.append('--with-demo')
        elif not self.with_demo and 'with-demo' not in available_options:
            migrate_cmd.append('--without-demo=true')
```

2024-12-02 10:15 UTC, Xavier-Do commented on runbot/models/build_config.py
> +            cmd.append('--without-demo=true')
```suggestion
        available_options = build._parse_config()
        if self.with_demo and 'with-demo' in available_options:
            migrate_cmd.append('--with-demo')
        elif not self.with_demo and 'with-demo' not in available_options:
            migrate_cmd.append('--without-demo=true')
```

2024-12-02 10:16 UTC, Xavier-Do commented on runbot/models/build_config.py
> +    with_demo = fields.Boolean("Install demo data", default=True, tracking=True)
Another solution could be to have two boolean fields
without-demo and with demo, both of them being False by default.

2024-12-02 13:40 UTC, Williambraecky commented on runbot/models/build_config.py
> +    with_demo = fields.Boolean("Install demo data", default=True, tracking=True)
Thanks for the insight 😄 

I like the selection field as it provides the most flexibility so I implemented it and tested all different ways.
Let me know what you think :)

2024-12-02 14:19 UTC, Xavier-Do commented on runbot/models/build_config.py
> +    with_demo = fields.Boolean("Install demo data", default=True, tracking=True)
The selection field doesn't allow an incorrect state where the two are True but it could have a 4th effect by design, do the opposite (no demo if demo is default, and vice versa)

2024-12-02 14:25 UTC, Williambraecky commented on runbot/models/build_config.py
> +    with_demo = fields.Boolean("Install demo data", default=True, tracking=True)
Do you want me to add that 4th state?

2024-12-02 15:06 UTC, Xavier-Do commented on runbot/models/build_config.py
> +    with_demo = fields.Boolean("Install demo data", default=True, tracking=True)
Not sure. Would be confusing. We can talk about that wednesday

2024-12-19 12:49 UTC, Xavier-Do commented on runbot/models/build_config.py
> +
```suggestion
        available_options = build._parse_config()
        demo_with_is_default = '--with-demo' not in available_options:
        demo_mode = build.params_id.config_data.get('demo_mode', self.demo_mode)
        if wanted_demo_behavior != build_default_demo_behavior:
            if demo_mode == 'with_demo' and not demo_with_is_default:
                cmd.append('--with-demo')
            elif demo_mode == 'without_demo'  and demo_with_is_default
                cmd.append('--without-demo=true')
```

Not sure, maybe?

2024-12-19 12:50 UTC, Xavier-Do commented on runbot/models/build_config.py
> +        "Install demo data", default='default', tracking=True
require=True

2024-12-19 13:39 UTC, merged