[IMP] runbot: add extra parameters and environment variables to build config step
odoo/runbot pull request #411
Opened 2020-10-10 09:26 UTC by davejames

Currently there is no way that I can see to configure extra parameters or environment variables to run_odoo build config steps. It is possible on install steps, but not on run steps. This PR adds that capability.

This is useful in cases where a module needs to be run as a server wide module. For example [OCA/queue](https://github.com/OCA/queue/tree/13.0/queue_job).

2020-10-14 21:14 UTC, Xavier-Do requested changes
Small remarks but except that LGTM. FYI we are planning to create a 14.0 branch "soon".

2020-10-14 21:14 UTC, Xavier-Do commented on runbot/views/config_views.xml
> +                           attrs="{'invisible': [('job_type', '!=', ('run_odoo'))]}"
To clean it a little, you can remove the `groups="base.group_no_one"`. We tried to hide some  magic fields but it was a bad idea.

I also think we can avoid to duplicate extra_params field and KISS by merging this with the second badly copy/pasted _Test setting_ group and adding  `run_odoo` to `('python', 'install_odoo', 'test_upgrade')` as well as moving extra_params to this section. It makes sence to add extra_params support for test_upgrade steps too if we need it. You can rename this section in "Extra Parameters" (or something else if you have a better idea)

2020-10-18 23:18 UTC, davejames commented
@Xavier-Do can you please let me know what error is being reported by runbot? This is a private build so I don't have access, but I can't see anything that might have caused the build to fail

2020-10-18 23:33 UTC, Xavier-Do commented
It looks like I broke 13.0 Friday, you can rebase it is now fixed  ;)

2020-10-19 09:29 UTC, merged