[IMP] runbot: use docker python lib
odoo/runbot pull request #597
Opened 2022-03-18 10:22 UTC by d-fence

While using the docker cli as a subprocess was KISS and convenient,
the python Docker SDK is mature, easy to use, available as a Debian
package and much more powerful.

It will permit to monitor the containers memory consumption and will
help to spot memory leaks.

2022-03-22 14:13 UTC, Xavier-Do commented on runbot/container.py
> +    container.stop()
We may want to set a timeout to 1
We may want to catch APIError (maybe if the docker isn't running anymore)

2022-03-22 14:26 UTC, Xavier-Do commented on runbot/container.py
> +    return True if container.status == 'running' else False
```suggestion
    return container.status == 'running'
```

2022-06-27 19:13 UTC, d-fence commented on runbot/container.py
> +        docker_client.images.build(path=build_dir, tag=image_tag)
After some rumination, I think that I prefer to keep the plain file.
My actual use case is that if it fails, it's far easier to repeat the docker build manually on the runbot where it failed.
You just change to the docker build dir and repeat the `docker build .` command.
With the file obj, you will have dump the dockerfile first, save it somewhere, apply the patch ...

2022-06-29 08:17 UTC, Xavier-Do commented on runbot/container.py
> +    return (True, None)
```suggestion
    except docker.errors.APIError as e:
        _logger.error('Build of image %s failed with this API error:', image_tag)
        return (False, e.explanation)
    except docker.errors.BuildError as e:
        _logger.error('Build of image %s failed with this BUILD error:', image_tag)
        message = e.msg + ''.join(log_line.get('stream') or '' for log_line in e.build_log)
        return (False, message)
    _logger.info('Dockerfile %s finished build', image_tag)
    return (True, None)
```

2022-06-29 08:28 UTC, Xavier-Do commented on runbot/container.py
> +            volumes.update({source: {'bind': f'/data/build/{dest}', 'mode': 'ro'}})
```suggestion
            volumes[source] = {'bind': f'/data/build/{dest}', 'mode': 'ro'}
```

2022-06-29 09:14 UTC, Xavier-Do requested changes

2022-06-29 09:14 UTC, Xavier-Do commented on runbot/container.py
> +    )
One part of the  "file based docker state" is that in some cases, even if the container was started, the returned status was that it wasn't (asking to fast after the docker run)

Hi would propose to test that with the docker api to check if it may be possible to simplify that.


```suggestion
    container = docker_client.containers.run(
        image_tag,
        name=container_name,
        volumes=volumes,
        shm_size='128m',
        mem_limit=memory,
        ports=ports,
        ulimits=ulimits,
        environment=env_variables,
        init=True,
        command=['/bin/bash', '-c',
                 f'exec &>> /data/buildlogs.txt ;{run_cmd}'],
        auto_remove=True,
        detach=True
    )
    if container.status != 'running':
            _logger.error('Container started but status is not running:  %s' % container.status)
```

2022-06-29 09:23 UTC, Xavier-Do commented on runbot/container.py
> +    return container.status == 'running'
Me may consider it running if it is in the 'paused' state ( and maybe created or restarting)

2022-06-30 08:58 UTC, merged