[IMP] runbot: add sort and filter capability on the build error page
odoo/runbot pull request #641
Opened 2022-08-09 15:34 UTC by rdeodoo

Before this commit, the build errors page was neither sortable neither
filterable.

This commit adds a way to filter by:
- all
- unassigned
- seen more than once

It also allows to sort by:
- last seen
- nb seen

Typical need is to sort by nb seen and filter out the only seen once to
be able to figure which one is supposed to be checked in priority.

2022-08-09 15:36 UTC, rdeodoo commented
@odoo/rd-runbot Hello :wave: 
That's the need we have I told you about: being able to sort and filter out some errors.
Thought I would give you a hand and suggest a change.

2022-08-09 15:38 UTC, rdeodoo commented on runbot/__manifest__.py
> +    'description': "Runbot for Odoo 15.0",
Or I am missing something? Tried to make it run on 13.0 but..

2022-08-09 15:38 UTC, rdeodoo commented on runbot/templates/build_error.xml
> +              <div class="d-flex">
This `<div>` is obviously not stable friendly in regular repo, is the same policy applied in this repo?
I could find another way to make the searchbar looks decent without modifying existing DOM if needed I guess.

2022-08-10 07:00 UTC, d-fence requested changes
Thanks for this nice improvement. A small fix and it will be LGTM

2022-08-10 08:18 UTC, rdeodoo commented on runbot/controllers/frontend.py
> +        domain = [('id', 'in', team.build_error_ids.ids)]
Changed :+1: (maybe we could have split the controllers / views for those 2 cases (teams vs team) but I let you decide as I am not very familiar with what can be done in stable in runbot anyway)

2022-08-17 09:42 UTC, merged

2022-08-17 09:42 UTC, Xavier-Do commented
Great work thanks!