[IMP] runbot: add cpus parameter
odoo/runbot pull request #695
Opened 2022-12-08 07:33 UTC by d-fence

When a build eats all the CPU's resources, it may interfere with other builds and cause collateral damages.

With this commit, a new settings parameter `Containers CPUs` is added in order to limit the usage of available CPU's on runbot instances.

If left to 0, no limts are applied.

Otherwise, the cpu_quota docker parameter is computed as Containers CPU's * (logical cpu's count / nb parallel builds) * cpu period which defaults to 100000.

e.g.:
- on a host with 16 logical CPU's
- with 8 parallel builds allowed
- with Containers CPUs set to 1.5
- with the default cpu_period cpu_quota will be:
    (16/8) * 1.5 * 100000 = 300000

2022-12-28 14:03 UTC, d-fence commented
Note that with the removal of the `log_path` parameter, some custom python step will have to be updated.
e.g.:  `test_migration_pre`

2023-02-28 11:41 UTC, Xavier-Do requested changes

2024-04-04 13:32 UTC, Xavier-Do commented on runbot/models/build_config.py
> +            if 'cpu_limit' not in docker_params:
todo add cpu_limit=None for _run_run_odoo

2024-04-04 14:27 UTC, d-fence commented
Done for 17.0 in #864

2024-04-04 14:27 UTC, closed without merging