[REF] runbot: remove link type ir.logging
odoo/runbot pull request #969
Opened 2024-10-25 12:50 UTC by Williambraecky

1: Stop using the special $$icon$$ syntax when logging the download url for
the database dump.

2: Removes the link type in ir.logging as they were using some weird dark
magic instead of the more generic markdown logging type.

2024-10-25 12:51 UTC, Williambraecky commented
@Xavier-Do Came across this while reading through the runbot repository and found it could use a little bit of cleanup.

I made the migration in a separate commit in case we would rather not do the migration.

2024-10-28 09:05 UTC, Xavier-Do requested changes
Nice cleanup, it was time to remove this old hack indeed! 

Small comments but we can check that together Wednesday and test everything.

2024-10-28 09:05 UTC, Xavier-Do commented on runbot/migrations/17.0.5.8/pre-migrate.py
> +    """, 'ir_logging', bucket_size=100000)
We don't use utils for upgrades on runbot usually I would prefer to avoid it ;) Anyway the ir_logging table is hudge so I'm not sure we need to migrate it completely. We can test it if not done yet. This can be done after the upgrade asynchronously.

2024-10-28 09:05 UTC, Xavier-Do commented on runbot/models/build_config.py
>          build._log('', **kwargs)
In the case of markdown logs, _http_log_url, dest, suffix should ideally be passed as arguments to the  build._log method so that it is escaped. This will avoid to potentially escape parts of the _http_log_url

In this case it is not a big issue I think but it would be cleaner

```suggestion
        build._log('',  ' [@icon-download](%s)' % ('%s%s-%s.zip' , build._http_log_url(), build.dest, db_suffix, log_type= 'markdown')
```

2024-11-28 15:25 UTC, merged